from django.urls import path

from .views import (
    admin_dashboard,
    admin_financial_audit_logs,
    admin_refund_payment,
    admin_revenue_report,
    admin_subscription_history,
    admin_transactions,
    ai_bridge_test,
    applicant_list,
    application_timeline,
    apply_job,
    approve_employer,
    audit_logs,
    auto_shortlist_candidates,
    block_user,
    candidate_ai_report,
    candidate_ai_report_pdf,
    candidate_dashboard,
    candidate_list,
    candidate_profile,
    candidate_report_summary,
    close_job,
    create_availability_slot,
    create_job,
    create_payment_order,
    edit_job,
    employer_dashboard,
    employer_jobs,
    employer_profile,
    evaluate_answer,
    featured_jobs,
    filter_applicants,
    job_analytics,
    job_list,
    latest_jobs,
    match_percentage,
    my_applications,
    my_subscription,
    next_question,
    create_notification,
    notification_list,
    unread_notification_count,
    mark_notification_read,
    mark_all_notifications_read,
    delete_notification,
    parse_resume,
    payment_history,
    profile,
    question_templates,
    ranked_candidates,
    razorpay_webhook,
    recommended_jobs,
    recruiter_funnel_analytics,
    recruiter_premium_analytics,
    recruiter_premium_report,
    recruiter_role_analytics,
    recruiter_time_analytics,
    reschedule_interview,
    schedule_interview,
    search_applicants,
    send_reminders_api,
    signup,
    subscribe,
    subscription_plans,
    test_email,
    unblock_user,
    update_application_status,
    verify_payment,
)

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("profile/", profile, name="profile"),

    path("admin-dashboard/", admin_dashboard, name="admin-dashboard"),
    path("admin/approve-employer/<int:employer_id>/", approve_employer, name="approve-employer"),
    path("admin/block-user/<int:user_id>/", block_user, name="block-user"),
    path("admin/unblock-user/<int:user_id>/", unblock_user, name="unblock-user"),
    path("admin/audit-logs/", audit_logs, name="audit-logs"),
    path("employer-dashboard/", employer_dashboard, name="employer-dashboard"),
    path("candidate-dashboard/", candidate_dashboard, name="candidate-dashboard"),
    path("recommended-jobs/", recommended_jobs, name="recommended-jobs"),
    path("match-percentage/<int:job_id>/", match_percentage, name="match-percentage"),
    path("ranked-candidates/<int:job_id>/", ranked_candidates, name="ranked-candidates"),
    path("application/<int:application_id>/timeline/", application_timeline, name="application-timeline"),

    path("candidate-profile/", candidate_profile, name="candidate-profile"),
    path("candidate-list/", candidate_list, name="candidate-list"),
    path("employer-profile/", employer_profile, name="employer-profile"),

    # Job APIs
    path("jobs/", create_job, name="create-job"),
    path("apply-job/<int:job_id>/", apply_job, name="apply-job"),
    path("my-applications/", my_applications, name="my-applications"),
    path("job-list/", job_list, name="job-list"),
    path("featured-jobs/", featured_jobs, name="featured-jobs"),
    path("latest-jobs/", latest_jobs, name="latest-jobs"),
    path("applications/<int:application_id>/status/", update_application_status, name="update_application_status"),
    path('my-jobs/', employer_jobs, name='my-jobs'),
    path('edit-job/<int:job_id>/', edit_job, name='edit-job'),
    path('close-job/<int:job_id>/', close_job, name='close-job'),
    path('applicants/<int:job_id>/', applicant_list, name='applicant-list'),
    path('applicants/<int:job_id>/filter/', filter_applicants, name='filter-applicants'),
    path('applicants/<int:job_id>/search/', search_applicants, name='search-applicants'),
    path('job-analytics/<int:job_id>/', job_analytics, name='job-analytics'),
    path("recruiter-funnel-analytics/", recruiter_funnel_analytics, name="recruiter-funnel-analytics"),
    path("recruiter/time-analytics/", recruiter_time_analytics, name="recruiter-time-analytics"),
    path("recruiter/role-analytics/", recruiter_role_analytics, name="recruiter-role-analytics"),
    path("recruiter/premium-analytics/", recruiter_premium_analytics, name="recruiter-premium-analytics"),
    path("recruiter/premium-report/", recruiter_premium_report),
    path("parse-resume/", parse_resume, name="parse-resume"),
    path("auto-shortlist/<int:job_id>/", auto_shortlist_candidates, name="auto-shortlist",),
    path("test-email/", test_email, name="test-email"),
    path("ai-bridge-test/", ai_bridge_test, name="ai-bridge-test"),
    path("question-templates/", question_templates, name="question-templates",),
    path("next-question/", next_question, name="next-question",),
    path("evaluate-answer/", evaluate_answer, name="evaluate-answer",),
    path("availability-slot/", create_availability_slot, name="availability-slot",),
    path("schedule-interview/", schedule_interview, name="schedule-interview",),
    path("reschedule-interview/<int:interview_id>/", reschedule_interview, name="reschedule-interview",),
    path("send-reminders/", send_reminders_api, name="send-reminders",),
    path("candidate-ai-report/<int:application_id>/", candidate_ai_report, name="candidate-ai-report"),
    path("candidate-report-summary/<int:application_id>/", candidate_report_summary, name="candidate-report-summary"),
    path("candidate-ai-report/<int:application_id>/pdf/", candidate_ai_report_pdf, name="candidate-ai-report-pdf"),


        # Subscription & Payment APIs
    path("subscription-plans/", subscription_plans, name="subscription-plans"),
    path("my-subscription/", my_subscription, name="my-subscription"),
    path("subscribe/", subscribe, name="subscribe"),
    path("payment-history/", payment_history, name="payment-history"),
    path("create-payment-order/", create_payment_order, name="create-payment-order"),
    path("verify-payment/", verify_payment, name="verify-payment"),
    path("razorpay-webhook/", razorpay_webhook, name="razorpay-webhook"),
    path("admin/transactions/", admin_transactions, name="admin-transactions"),
    path("admin/subscription-history/", admin_subscription_history, name="admin-subscription-history"),
    path("admin/revenue-report/", admin_revenue_report, name="admin-revenue-report"),
    path("admin/refund/", admin_refund_payment, name="admin-refund-payment"),
    path("admin/financial-audit-logs/", admin_financial_audit_logs, name="admin-financial-audit-logs"),


        # Notification Dashboard APIs
    path(
        "notifications/",
        notification_list,
        name="notification-list"
    ),
    path(
        "notifications/create/",
        create_notification,
        name="create-notification"
    ),
    path(
        "notifications/unread-count/",
        unread_notification_count,
        name="unread-notification-count"
    ),
    path(
        "notifications/<int:notification_id>/read/",
        mark_notification_read,
        name="mark-notification-read"
    ),
    path(
        "notifications/mark-all-read/",
        mark_all_notifications_read,
        name="mark-all-notifications-read"
    ),
    path(
        "notifications/<int:notification_id>/",
        delete_notification,
        name="delete-notification"
    ),
]