# Generated by Django 4.2 on 2026-07-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
