# Generated by Django 6.0.7 on 2026-07-20 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_application_action_application_created_at_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='action',
        ),
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(default='Initial Action', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 20, 12, 31, 38, 19522, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
