# Generated by Django 6.0.7 on 2026-07-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_application_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
