# Generated by Django 6.0.7 on 2026-08-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_aiinterviewsession_aiquestion_aianswer_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='transcript',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
