# Generated by Django 6.0.7 on 2026-08-05 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_aiinterviewsession_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Introduction', 'Introduction'), ('Experience', 'Experience'), ('Skills', 'Skills'), ('Availability', 'Availability'), ('Salary', 'Salary')], max_length=30)),
                ('question', models.TextField()),
                ('role', models.CharField(default='General', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(max_length=100)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_question', to='accounts.questiontemplate')),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='accounts.questiontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answer', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.questiontemplate')),
            ],
        ),
    ]
