# Generated by Django 6.0.7 on 2026-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_questiontemplate_questionflow_interviewstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianswer',
            name='annotations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='completeness_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='keyword_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='relevance_score',
            field=models.FloatField(default=0),
        ),
    ]
