# Generated by Django 6.0.7 on 2026-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_paymenttransaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='job_status_created_idx'),
        ),
    ]
